spring:
  profiles:
    active: dev
  application:
    name: SMC-Zuul-Getway

server:
  port: 80

zuul:
  # 所谓敏感，也即是在转发时要删除的设置
  sensitive-headers: Access-Control-Allow-Origin,Cookie,Set-Cookie # 会过滤客户端附带的headers. It's to fix error: multiple Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,Cookie,Set-Cookie # 会过滤服务之间通信附带的headers, e.g.: 如果客户端在发请求是带了Cookie，那么Cookie依然会传递给下游服务。但是如果下游服务再转发就会被过滤。
#  prefix: /api/smc
#  strip-prefix: false
  routes:
    SMC-Users: /smcuser/**
    SMC-Price: /smcprice/**
    SMC-Import: /smcimport/**
    SMC-Exchange: /smcexchange/**
    SMC-Company: /smccompany/**

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 60000
   #MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
   #MaxAutoRetriesNextServer: 1
   eureka:
     enable: true


management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
  
---
spring:
  profiles: dev
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    #    prefer-ip-address: false
#        hostname: localhost
    #    instance-id: 127.0.0.1:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    
# a日志设置配置信息
# logging:
#   config: classpath:logback-spring.xml
 
---
spring:
  profiles: prod
  
eureka:
  client:
    service-url:
      defaultZone: http://101.201.102.101:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    #    prefer-ip-address: false
    #    hostname: 106.54.194.33
    #    instance-id: 106.54.194.33:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    
# a日志设置配置信息
# logging:
#   config: classpath:logback-prod.xm

